[phases.setup]
nixPkgs = ['python311', 'sqlite']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = []

[phases.start]
cmd = 'python manage.py migrate && python manage.py collectstatic --noinput && gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT'
